spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitlog
    username: root
    password: ureca

springdoc:
  api-docs:
    path: /v3/api-docs      # (선택) JSON 명세 URL
  swagger-ui:
    path: /swagger-ui    # (선택) UI 접근 URL
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    with-credentials: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ureca.fitlog.dto

jwt:
  access-expiration: 3600000
  refresh-expiration: 604800000
  secret: 914da3709fcbc4284f731eae7f54503cc6f2010ae743d130fb74006401461ec5

logging:
  level:
    org.mybatis: DEBUG
    com.ureca.fitlog: DEBUG

